
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  master:
    build: ./master
    container_name: master
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"

  worker1:
    build: ./master
    container_name: worker1
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A celery_worker.celery_app worker --loglevel=info --hostname=worker1@%h

  worker2:
    build: ./master
    container_name: worker2
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A celery_worker.celery_app worker --loglevel=info --hostname=worker2@%h
